# Generated by Django 6.1.1 on 2026-09-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PikiOraMedicalCentre', '0003_profile_address_profile_email_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
