# Generated by Django 6.1.1 on 2026-09-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PikiOraMedicalCentre', '0004_remove_profile_email_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
