# Generated by Django 6.1.1 on 2026-09-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PikiOraMedicalCentre', '0005_appointment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
