# Generated by Django 6.1.1 on 2026-09-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PikiOraMedicalCentre', '0006_remove_appointment_date_remove_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
