# Generated by Django 6.1.1 on 2026-09-23 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PikiOraMedicalCentre', '0007_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_timeslot', to='PikiOraMedicalCentre.timeslot'),
        ),
    ]
